name: flutter_chat_demo
description: This is the demo for chat app by Flutter

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^1.0.0
  font_awesome_flutter: 8.8.1
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.0+1  #0.14.0+5
  google_sign_in: ^4.5.3 #4.0.7
  fluttertoast: ^7.0.2 #3.1.3
  image_picker: ^0.6.7+7 #0.6.1+8
  shared_preferences: ^0.5.10 #0.5.3+4
  firebase_storage: ^4.0.0 #3.0.6
  cached_network_image: ^2.3.1 #2.0.0-rc.1
  intl: ^0.16.1 #0.15.7
  firebase_messaging: 7.0.0 #6.0.13
  flutter_local_notifications: 1.4.4+4 #1.4.0
  photo_view: ^0.10.2 #0.5.0
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.25
  geolocator: ^5.3.0
  provider: ^4.0.4
  url_launcher: ^5.4.2
  http: ^0.12.0+4
  flutter_rating_bar: ^3.0.1+1
  #url_launcher: ^5.1.4
  url_launcher_web: ^0.1.0
  cloud_firestore:  ^0.14.0+2 #^0.12.9+5



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - images/img_not_available.jpeg
      - images/mimi1.gif
      - images/mimi2.gif
      - images/mimi3.gif
      - images/mimi4.gif
      - images/mimi5.gif
      - images/mimi6.gif
      - images/mimi7.gif
      - images/mimi8.gif
      - images/mimi9.gif
      - assets/images/menus/ic_search_menu.png
      - assets/images/menus/ic_account.png
      - assets/images/menus/ic_cart.png
      - assets/images/menus/ic_home.png
      - assets/images/menus/ic_delete.png
      - assets/images/menus/ic_near_by.png
      - assets/images/menus/ic_credit_card.png
      - assets/images/menus/ic_app_icon.png
      - assets/images/menus/ic_food_express.png
      - assets/images/menus/ic_app_icon_black.png
      - assets/images/topmenu/ic_burger.png
      - assets/images/topmenu/ic_cake.png
      - assets/images/topmenu/ic_ice_cream.png
      - assets/images/topmenu/ic_pasta.png
      - assets/images/topmenu/ic_pizza.png
      - assets/images/topmenu/ic_sushi.png
      - assets/images/topmenu/ic_soft_drink.png
      - assets/images/popular_foods/ic_popular_food_1.png
      - assets/images/popular_foods/ic_popular_food_2.png
      - assets/images/popular_foods/ic_popular_food_3.png
      - assets/images/popular_foods/ic_popular_food_4.png
      - assets/images/popular_foods/ic_popular_food_5.png
      - assets/images/popular_foods/ic_popular_food_6.png
      - assets/images/popular_foods/ic_popular_food_7.png
      - assets/images/bestfood/ic_best_food_1.jpeg
      - assets/images/bestfood/ic_best_food_2.jpeg
      - assets/images/bestfood/ic_best_food_3.jpeg
      - assets/images/bestfood/ic_best_food_4.jpeg
      - "assets/images/img/hospital.jpg"
      - "assets/images/img/help.png"
      - "assets/images/hbed.png"
      - "assets/images/parking-icon.png"
      - images/img_not_available.jpeg
      - images/mimi1.gif
      - images/mimi2.gif
      - images/mimi3.gif
      - images/mimi4.gif
      - images/mimi5.gif
      - images/mimi6.gif
      - images/mimi7.gif
      - images/mimi8.gif
      - images/mimi9.gif
      - assets/employee.jpg
      - assets/background.png
      - assets/clock.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
